"use client";

import { useEffect, useMemo, useState } from "react";
import { formatEther } from "viem";

import {
  useAccount,
  useReadContract,
  useWaitForTransactionReceipt,
  useWriteContract,
} from "wagmi";

import { BRICKS404_ABI } from "@/lib/abi";
import { CONTRACTS } from "@/lib/contracts";

export default function MintCard() {
  const [mounted, setMounted] = useState(false);
  const [quantity, setQuantity] = useState(1);

  const { address, isConnected } = useAccount();

  const { data: mintPrice } = useReadContract({
    address: CONTRACTS.bricks404,
    abi: BRICKS404_ABI,
    functionName: "mintPrice",
  });

  const { data: minted } = useReadContract({
    address: CONTRACTS.bricks404,
    abi: BRICKS404_ABI,
    functionName: "mintedBricks",
  });

  const { data: maxSupply } = useReadContract({
    address: CONTRACTS.bricks404,
    abi: BRICKS404_ABI,
    functionName: "maxSupply",
  });

  const { data: maxMintPerWallet } = useReadContract({
    address: CONTRACTS.bricks404,
    abi: BRICKS404_ABI,
    functionName: "maxMintPerWallet",
  });

  const { data: walletMinted } = useReadContract({
    address: CONTRACTS.bricks404,
    abi: BRICKS404_ABI,
    functionName: "mintedByWallet",
    args: address ? [address] : undefined,
    query: {
      enabled: mounted && !!address,
    },
  });

  const {
    writeContract,
    data: hash,
    isPending,
  } = useWriteContract();

  const {
    isLoading: confirming,
    isSuccess,
  } = useWaitForTransactionReceipt({
    hash,
  });

  useEffect(() => {
    setMounted(true);
  }, []);

  const remainingWallet =
    maxMintPerWallet !== undefined &&
    walletMinted !== undefined
      ? Number(maxMintPerWallet - walletMinted)
      : 25;

  const remainingSupply =
    maxSupply !== undefined &&
    minted !== undefined
      ? Number(maxSupply - minted)
      : 6666;

  const maxSelectable = Math.max(
    0,
    Math.min(25, remainingWallet, remainingSupply)
  );

  useEffect(() => {
    if (maxSelectable < 1) {
      setQuantity(1);
      return;
    }

    setQuantity((current) =>
      Math.min(Math.max(current, 1), maxSelectable)
    );
  }, [maxSelectable]);

  const totalPrice = useMemo(() => {
    if (!mintPrice) return 0n;
    return mintPrice * BigInt(quantity);
  }, [mintPrice, quantity]);

  const mint = () => {
    if (!mounted) return;
    if (!isConnected) return;
    if (mintPrice === undefined) return;
    if (quantity < 1) return;
    if (quantity > maxSelectable) return;

    writeContract({
      address: CONTRACTS.bricks404,
      abi: BRICKS404_ABI,
      functionName: "mint",
      args: [BigInt(quantity)],
      value: totalPrice,
    });
  };

  if (!mounted) {
    return (
      <section className="mint-card">
        <div className="eyebrow">404 BRICKS</div>

        <h1>
          ON-CHAIN
          <br />
          BRICKS.
        </h1>

        <p className="hero-copy">
          6,666 pixel Bricks.
          <br />
          Fully generated by the contract.
        </p>

        <div className="mint-price">
      
        </div>

        <div
          style={{
            marginTop: 18,
            width: "100%",
            height: 64,
            display: "flex",
            border: "1px solid #292929",
            background: "#0d0d0d",
          }}
        >
          <button
            type="button"
            disabled
            style={{
              width: 64,
              border: 0,
              borderRight: "1px solid #292929",
              background: "#151515",
              color: "#fff",
              fontSize: 28,
              fontWeight: 900,
            }}
          >
            −
          </button>

          <div
            style={{
              flex: 1,
              display: "flex",
              flexDirection: "column",
              alignItems: "center",
              justifyContent: "center",
            }}
          >
            <strong
              style={{
                fontSize: 24,
                lineHeight: 1,
              }}
            >
              1
            </strong>

            <span
              style={{
                marginTop: 6,
                color: "#8d8d8d",
                fontSize: 9,
                fontWeight: 900,
                letterSpacing: "0.12em",
              }}
            >
              MAX 25
            </span>
          </div>

          <button
            type="button"
            disabled
            style={{
              width: 64,
              border: 0,
              borderLeft: "1px solid #292929",
              background: "#151515",
              color: "#fff",
              fontSize: 28,
              fontWeight: 900,
            }}
          >
            +
          </button>
        </div>

        <button
          className="mint-button"
          disabled
          style={{ marginTop: 10 }}
        >
          CONNECT WALLET
        </button>
      </section>
    );
  }

  return (
    <section className="mint-card">
      <div className="eyebrow">MINT</div>

      <h1>
        404
        <br />
        BRICKS.
      </h1>

      <p className="hero-copy">
        6,666 Onchain Bricks.
        <br />
        Built on Robinhood.
      </p>

      <div className="mint-price">
        {mintPrice
          ? `${formatEther(mintPrice)} ETH`
          : ""}
      </div>

      {/* QUANTITY SELECTOR */}
      <div
        style={{
          marginTop: 18,
          width: "100%",
          height: 64,
          display: "flex",
          border: "1px solid #292929",
          background: "#0d0d0d",
        }}
      >
        <button
          type="button"
          disabled={
            quantity <= 1 ||
            isPending ||
            confirming
          }
          onClick={() =>
            setQuantity((current) =>
              Math.max(1, current - 1)
            )
          }
          style={{
            width: 64,
            minWidth: 64,
            border: 0,
            borderRight: "1px solid #292929",
            background: "#151515",
            color: "#fff",
            fontSize: 28,
            fontWeight: 900,
            cursor:
              quantity <= 1
                ? "not-allowed"
                : "pointer",
            opacity:
              quantity <= 1 ? 0.25 : 1,
          }}
        >
          −
        </button>

        <div
          style={{
            flex: 1,
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
            justifyContent: "center",
          }}
        >
          <strong
            style={{
              color: "#fff",
              fontSize: 24,
              fontWeight: 1000,
              lineHeight: 1,
            }}
          >
            {quantity}
          </strong>

          <span
            style={{
              marginTop: 6,
              color: "#8d8d8d",
              fontSize: 9,
              fontWeight: 900,
              letterSpacing: "0.12em",
            }}
          >
            MAX {maxSelectable}
          </span>
        </div>

        <button
          type="button"
          disabled={
            quantity >= maxSelectable ||
            isPending ||
            confirming
          }
          onClick={() =>
            setQuantity((current) =>
              Math.min(
                maxSelectable,
                current + 1
              )
            )
          }
          style={{
            width: 64,
            minWidth: 64,
            border: 0,
            borderLeft: "1px solid #292929",
            background: "#151515",
            color: "#fff",
            fontSize: 28,
            fontWeight: 900,
            cursor:
              quantity >= maxSelectable
                ? "not-allowed"
                : "pointer",
            opacity:
              quantity >= maxSelectable
                ? 0.25
                : 1,
          }}
        >
          +
        </button>
      </div>

      {/* QUICK SELECT */}
      <div
        style={{
          width: "100%",
          display: "flex",
          gap: 6,
          marginTop: 8,
        }}
      >
        {[1, 5, 10, 15, 20, 25].map(
          (amount) => {
            const disabled =
              amount > maxSelectable;

            const active =
              quantity === amount;

            return (
              <button
                type="button"
                key={amount}
                disabled={disabled}
                onClick={() =>
                  setQuantity(amount)
                }
                style={{
                  flex: 1,
                  minWidth: 0,
                  height: 32,
                  border: active
                    ? "1px solid #ccff00"
                    : "1px solid #292929",
                  background: active
                    ? "#ccff00"
                    : "#121212",
                  color: active
                    ? "#000"
                    : "#8d8d8d",
                  fontSize: 10,
                  fontWeight: 900,
                  cursor: disabled
                    ? "not-allowed"
                    : "pointer",
                  opacity: disabled
                    ? 0.2
                    : 1,
                }}
              >
                {amount}
              </button>
            );
          }
        )}
      </div>

      {/* TOTAL */}
      <div
        style={{
          width: "100%",
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          marginTop: 14,
          padding: "13px 0",
          borderTop: "1px solid #292929",
          borderBottom: "1px solid #292929",
          color: "#8d8d8d",
          fontSize: 10,
          fontWeight: 900,
          letterSpacing: "0.12em",
        }}
      >
        <span>TOTAL</span>

        <strong
          style={{
            color: "#ccff00",
            fontSize: 16,
            fontWeight: 1000,
            letterSpacing: "normal",
          }}
        >
          {formatEther(totalPrice)} ETH
        </strong>
      </div>

      {/* MINT */}
      <button
        className="mint-button"
        disabled={
          !isConnected ||
          isPending ||
          confirming ||
          mintPrice === undefined ||
          maxSelectable <= 0
        }
        onClick={mint}
      >
        {!isConnected
          ? "CONNECT WALLET"
          : isPending
          ? "CONFIRM IN WALLET..."
          : confirming
          ? "CONFIRMING..."
          : isSuccess
          ? "MINTED"
          : maxSelectable <= 0
          ? "MAX MINTED"
          : "MINT BRICKS"}
      </button>

      {/* STATS */}
      <div className="mint-info">
        <span>
          SUPPLY
          <strong>
            {minted?.toString() ?? "0"} /{" "}
            {maxSupply?.toString() ?? "6666"}
          </strong>
        </span>

        <span>
          YOUR MINTS
          <strong>
            {walletMinted?.toString() ?? "0"} /{" "}
            {maxMintPerWallet?.toString() ?? "25"}
          </strong>
        </span>
      </div>
    </section>
  );
}